CC = gcc
CFLAGS = -DHAVE_FCNTL_H -DHAVE_ERRNO_H \
         -DTIME_WITH_SYS_TIME -DHAVE_DEVICES_TIMER_H \
         -DBSD_STYLE_GETTIMEOFDAY -D__USE_INLINE__ -D__USE_BASETYPE__ \
         -O4

VMSOBJS = amiga_main.o amiga_mainwin.o cpu.o lcdimg.o getopt.o

vms: $(VMSOBJS)
	$(CC) -o $@ $(VMSOBJS) -lauto

clean :
	-delete FORCE vms $(VMSOBJS)

